{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-agent
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-agent
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.agent.image.repository }}-{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy | default "IfNotPresent" }}
          env:
            {{- include "example-app.jsonToEnv" .Values.agent.envFromJson | nindent 12 }}
            {{- if .Values.agent.env }}
            {{- toYaml .Values.agent.env | nindent 12 }}
            {{- end }}
            - name: PORT
              value: "8000"
            - name: HOST
              value: "0.0.0.0"
          ports:
            - name: http
              containerPort: {{ if .Values.agent.service }}{{ .Values.agent.service.port | default 8000 }}{{ else }}8000{{ end }}
              protocol: TCP
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}