{{- $root := . }}
{{- range $deploymentIndex, $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $root.Values.app.name }}-{{ $deployment.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $root.Values.app.name }}-{{ $deployment.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $root.Values.app.name }}-{{ $deployment.name }}
    spec:
      securityContext: {}
      containers:
        - name: {{ $root.Values.app.name }}-{{ $deployment.name }}
          image: "{{ $deployment.image.repository }}-{{ $deployment.image.tag }}"
          imagePullPolicy: {{ $deployment.image.pullPolicy | default "IfNotPresent" }}
          {{- if $deployment.command }}
          command:
            {{- toYaml $deployment.command | nindent 12 }}
          {{- end }}
          env:
            {{- if $deployment.config.secretsJson }}
            {{- include "example-app.jsonToEnv" $deployment.config.secretsJson | nindent 12 }}
            {{- end }}
            {{- if $deployment.config.env }}
            {{- toYaml $deployment.config.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ $deployment.port }}
              protocol: TCP
          {{- with $deployment.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $deployment.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
