{{- $root := . }}
{{- range $deploymentIndex, $deployment := .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.app.name }}-{{ $deployment.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $deployment.port }}
      targetPort: {{ $deployment.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ $root.Values.app.name }}-{{ $deployment.name }}
{{- end }}
