apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-demo-config
data:
  app.name: {{ .Values.app.name }}
  deployments: |
    [
      {{- $root := . }}
      {{- range $deploymentIndex, $deployment := .Values.deployments }}
        {
          "type": "{{ $deployment.config.type }}",
          {{- if $deployment.config.dependencies }}
          "dependencies": "{{ $deployment.config.dependencies }}",
          {{- end }}
          "deployment": "{{ $deployment.name }}",
          "url": "https://{{ $root.Values.app.name }}-{{ $deployment.name }}-{{ $root.Values.environment}}.demos.devcopilotkit.com"
        }{{- if ne $deploymentIndex (sub (len $root.Values.deployments) 1) }}, {{- end }}
      {{- end }}
    ]