{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-ui
  template:
    metadata:
      {{- with .Values.ui.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-ui
    spec:
      {{- with .Values.ui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.ui.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.ui.image.repository }}-{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy | default "IfNotPresent" }}
          command: ["npm", "start", "--", "-H", "0.0.0.0", "--port", "{{ .Values.ui.port | default 3000 }}"]
          env:
            {{- include "example-app.jsonToEnv" .Values.ui.envFromJson | nindent 12 }}
            {{- if .Values.ui.env }}
            {{- toYaml .Values.ui.env | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ if .Values.ui.service }}{{ .Values.ui.service.port | default 3000 }}{{ else }}3000{{ end }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}