name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
      - '.github/workflows/demos_preview.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'CopilotKit'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.5"
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Ensure Changesets
        if: ${{ github.event_name == 'pull_request' }}
        id: ensure-changesets
        run: |
          echo "num_changesets=$(pnpm changeset status --output changeset-status-output.json && cat changeset-status-output.json | jq '.changesets | length')\n" >> $GITHUB_OUTPUT

      - name: ✅ Changesets Found
        if: ${{ github.event_name == 'pull_request' && steps.ensure-changesets.outputs.num_changesets > 0 }}
        run: |
          echo "Changesets found"

      - name: ❌ Changesets Not Found
        if: ${{ github.event_name == 'pull_request' && steps.ensure-changesets.outputs.num_changesets == 0 }}
        run: |
          echo "Changesets not found"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: npx turbo run build

      - name: Run tests
        run: npx turbo run test
