name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
      - '.github/workflows/demos_preview.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'CopilotKit'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.5"
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure Changesets
        if: ${{ github.event_name == 'pull_request' }}
        id: ensure-changesets
        working-directory: './CopilotKit'
        continue-on-error: true
        run: |
          pnpm changeset --since=origin/main status

      - name: Delete a comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: changeset-status
          mode: delete

      - name: Comment post-deployment (Changesets found)
        if: ${{ github.event_name == 'pull_request' && steps.ensure-changesets.outcome == 'success' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: changeset-status
          message: |
            ### ✅ Changeset status OK

            Latest commit: ${{ github.sha }}

            You have either not made any changes to the `@copilotkit/*` packages, or you did and you've added a changeset.

            Merging this PR will cause a version bump.

      - name: Comment post-deployment (Changesets not found)
        if: ${{ github.event_name == 'pull_request' && steps.ensure-changesets.outcome == 'failure' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: changeset-status
          message: |
            ###  ⚠️  No Changeset found

            Latest commit: ${{ github.sha }}

            Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**

            **To add a changeset:**

            1. `cd CopilotKit`
            2. `pnpm changeset`
            3. Commit the changeset file(s) and push to the branch.

      - name: Build
        run: npx turbo run build

      - name: Run tests
        run: npx turbo run test
