name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
      - '.github/workflows/demos_preview.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'examples/**'
jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'CopilotKit'
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.5"
    
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Ensure Changesets
        if: ${{ github.event_name == 'pull_request' }}
        id: ensure-changesets
        working-directory: './CopilotKit'
        continue-on-error: true
        run: |
          status=$(pnpm changeset --since=origin/main status)
          echo status: $status
          echo "code=$?" >> $GITHUB_OUTPUT

      - name: Delete a comment
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: changeset-status
          mode: delete

      - name: Comment post-deployment (Changesets found)
        if: ${{ github.event_name == 'pull_request' && steps.ensure-changesets.outputs.code == 0 }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: changeset-status
          message: |
            Changesets found

      - name: Comment post-deployment (Changesets not found)
        if: ${{ github.event_name == 'pull_request' && steps.ensure-changesets.outputs.code == 1 }}
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: changeset-status
          message: |
            Changesets NOT found

      - name: Build
        run: npx turbo run build

      - name: Run tests
        run: npx turbo run test
