name: Demos Preview

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment with example preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave: