name: Demos Preview

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment with example preview
    permissions:
      deployments: write
      pull-requests: write
      statuses: write
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: preview
          message: |
            <table>
              <tr>
                <th>Demo</th>
                <th>Preview URL</th>
              </tr>
              <tr>
                <td>Example 1</td>
                <td>http://example1.com</td>
              </tr>
            </table>

      # - name: Deploy
      #   uses: chrnorm/deployment-action@v2
      #   id: deployment
      #   with:
      #     token: '${{ github.token }}'
      #     environment-url: "http://test.com"
      #     environment: "preview-branch"
      #     # ref: "some-pr"
      #     payload: "{\"key\": \"value\"}"


      