name: Demos Preview

on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Comment with example preview
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world ! :wave: