name: Test Deploy Custom CopilotKit Version to Cloud

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g. `1.5.12-next.0`)"
        required: true

jobs:
  deploy-custom-copilotkit-version-to-cloud:
    name: "Deploy via Reusable Workflow"
    uses: CopilotKit/CopilotCloud/.github/workflows/deploy-custom-copilotkit-version.yaml@main
    with:
      version: ${{ inputs.version }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        with: 
          app_id: 1108748
          private_key: ${{ secrets.DEVOPS_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.get_installation_token.outputs.token }}

      # - name: Test Composite Action
      #   uses: copilotkit/copilotcloud/.github/workflows/test-deploy-custom-copilotkit-version-to-cloud.yml@main
      #   with:
      #     version: ${{ inputs.version }}
      #   secrets:
      #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
